### PR TITLE
chore: bump to php 8 to allow laravel 9

### PR DESCRIPTION
**Pull request by ibrunotome**
Laravel 9 requires php ^8.0.2

### CODE REVIEW

**Comment by ekandreas** [comment]
Any plan to release?

**Comment by Tarpsvo** [comment]
>= 7.2 already supports PHP 8. Does it not work?

**Comment by ibrunotome** [comment]
> = 7.2 already supports PHP 8. Does it not work?

No, because 9 only supports ^8.0.2 https://github.com/laravel/framework/blob/9.x/composer.json#L18

So `^7.2.0|^8.0.2` will keep the support for both <= L8 and L9

**Comment by Tarpsvo** [comment]
Hi! Please explain like I'm five why `>=7.2` is worse than `^7.2.0|^8.0.2` besides the risk that it's unbound? The versions we currently have in `composer.json` seem to work fine for Laravel 9 and PHP 8 for me.

**Comment by ibrunotome** [comment]
Require all the below repos on your latest versions in a Laravel 9 project. Nothing will install without explicit declaration of major php version that L9 uses. With >= the accepted versions stops at 7.x.x, with the PR both major versions are supported.

https://user-images.githubusercontent.com/4256471/157037863-5884b1b4-78c8-443f-84e8-ab709b74b485.png

**Comment by Tarpsvo** [comment]
image

Unable to reproduce this. >= 7.X also includes version 8 and beyond. What error are you getting?

**Comment by ibrunotome** [comment]
Well, you're right, just got time to retry it today and now everything works normally pointing to the latest versions.

**Pull request closed without merging**
